
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA28hdDjZ3bs_uHB3NUPZzPF8xVQWFcYbk',
    appId: '1:1081102963051:web:40b8020df7ce24156bfc2e',
    messagingSenderId: '1081102963051',
    projectId: 'impostor-a1798',
    authDomain: 'impostor-a1798.firebaseapp.com',
    databaseURL: 'https://impostor-a1798-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-a1798.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28hdDjZ3bs_uHB3NUPZzPF8xVQWFcYbk',
    appId: '1:1081102963051:android:e6f5c879905963286bfc2e',
    messagingSenderId: '1081102963051',
    projectId: 'impostor-a1798',
    databaseURL: 'https://impostor-a1798-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-a1798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28hdDjZ3bs_uHB3NUPZzPF8xVQWFcYbk',
    appId: '1:1081102963051:ios:a2c56a81d4564c746bfc2e',
    messagingSenderId: '1081102963051',
    projectId: 'impostor-a1798',
    databaseURL: 'https://impostor-a1798-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-a1798.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA28hdDjZ3bs_uHB3NUPZzPF8xVQWFcYbk',
    appId: '1:1081102963051:ios:a2c56a81d4564c746bfc2e',
    messagingSenderId: '1081102963051',
    projectId: 'impostor-a1798',
    databaseURL: 'https://impostor-a1798-default-rtdb.firebaseio.com',
    storageBucket: 'impostor-a1798.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
